tools:
  - name: node
    min_version: "20.0.0"
    optional: false
    
  - name: pnpm
    min_version: "8.0.0"
    optional: false
    
  - name: git
    min_version: "2.40.0"
    optional: false
    
  - name: gh
    min_version: "2.0.0"
    optional: true
